### ISSUE TITLE
Handle directories/files deleted on Crowdin

### ISSUE THREAD

**Issue by thompsonsj** [thompsonsj/payload-crowdin-sync#147]
If a collection directory is deleted on Crowdin, and a corresponding `CrowdinArticleDirectories` collection document exists for that directory, the following line will cause an error:

https://github.com/thompsonsj/payload-crowdin-sync/blob/f0769e15f0a7c67bcec87e97c9ad1451da49a9f2/plugin/src/lib/api/payload-crowdin-sync/files.ts#L117

```
Error: Invalid directory id given. Directory doesn't exists
    at handleHttpClientError (/<project-dir>/node_modules/@crowdin/crowdin-api-client/out/core/index.js:79:15)
    at /<project-dir>/node_modules/@crowdin/crowdin-api-client/out/core/index.js:250:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Handle this type of scenario. Might be worth doing this once the plugin has been refactored to only use `nock` rather than a mock API.

**Comment by thompsonsj** [comment]
Another scenario - a file deleted on Crowdin:

```
[2024-08-14T08:54:50] | CrowdinError: File Not Found
-- | --
[2024-08-14T08:54:50] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-08-14T08:54:50] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-08-14T08:54:50] | at runMicrotasks (<anonymous>)
[2024-08-14T08:54:50] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-08-14T08:54:50] | code: 404
[2024-08-14T08:54:50] | }
```

No context is given. It would be useful if we detected this scenario in the UI and reported on which file could not be found - presenting an option to recreate it?

**Comment by thompsonsj** [comment]
In a scenario where a lot of fields were deleted on Crowdin (it's assumed they were created as a result of duplicated documents, see https://github.com/thompsonsj/payload-crowdin-sync/issues/201), the following large number of errors occured.

The document updated all the same but the CMS indicates there was a problem.

```

[2024-10-22T10:50:07] | CrowdinError: File Not Found
-- | --
[2024-10-22T10:50:07] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:07] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:07] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:07] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:07] | code: 404
[2024-10-22T10:50:07] | }
[2024-10-22T10:50:09] | CrowdinError: File Not Found
[2024-10-22T10:50:09] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:09] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:09] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:09] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:09] | code: 404
[2024-10-22T10:50:09] | }
[2024-10-22T10:50:11] | CrowdinError: File Not Found
[2024-10-22T10:50:11] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:11] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:11] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:11] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:11] | code: 404
[2024-10-22T10:50:11] | }
[2024-10-22T10:50:14] | CrowdinError: File Not Found
[2024-10-22T10:50:14] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:14] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:14] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:14] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:14] | code: 404
[2024-10-22T10:50:14] | }
[2024-10-22T10:50:17] | CrowdinError: File Not Found
[2024-10-22T10:50:17] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:17] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:17] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:17] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:17] | code: 404
[2024-10-22T10:50:17] | }
[2024-10-22T10:50:18] | CrowdinError: File Not Found
[2024-10-22T10:50:18] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:18] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:18] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:18] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:18] | code: 404
[2024-10-22T10:50:18] | }
[2024-10-22T10:50:27] | CrowdinError: File Not Found
[2024-10-22T10:50:27] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:27] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:27] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:27] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:27] | code: 404
[2024-10-22T10:50:27] | }
[2024-10-22T10:50:29] | CrowdinError: File Not Found
[2024-10-22T10:50:29] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:29] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:29] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:29] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:29] | code: 404
[2024-10-22T10:50:29] | }
[2024-10-22T10:50:35] | CrowdinError: File Not Found
[2024-10-22T10:50:35] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:35] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:35] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:35] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:35] | code: 404
[2024-10-22T10:50:35] | }
[2024-10-22T10:50:36] | CrowdinError: File Not Found
[2024-10-22T10:50:36] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:36] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:36] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:36] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:36] | code: 404
[2024-10-22T10:50:36] | }
[2024-10-22T10:50:37] | CrowdinError: File Not Found
[2024-10-22T10:50:37] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:37] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:37] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:37] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:37] | code: 404
[2024-10-22T10:50:37] | }
[2024-10-22T10:50:37] | CrowdinError: File Not Found
[2024-10-22T10:50:37] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:37] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:37] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:37] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:37] | code: 404
[2024-10-22T10:50:37] | }
[2024-10-22T10:50:38] | CrowdinError: File Not Found
[2024-10-22T10:50:38] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:38] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:38] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:38] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:38] | code: 404
[2024-10-22T10:50:38] | }
[2024-10-22T10:50:38] | CrowdinError: File Not Found
[2024-10-22T10:50:38] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:38] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:38] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:38] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:38] | code: 404
[2024-10-22T10:50:38] | }
[2024-10-22T10:50:39] | CrowdinError: File Not Found
[2024-10-22T10:50:39] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:39] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:39] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:39] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:39] | code: 404
[2024-10-22T10:50:39] | }
[2024-10-22T10:50:39] | CrowdinError: File Not Found
[2024-10-22T10:50:39] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:39] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:39] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:39] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:39] | code: 404
[2024-10-22T10:50:39] | }
[2024-10-22T10:50:40] | CrowdinError: File Not Found
[2024-10-22T10:50:40] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:40] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:40] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:40] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:40] | code: 404
[2024-10-22T10:50:40] | }
[2024-10-22T10:50:41] | CrowdinError: File Not Found
[2024-10-22T10:50:41] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:41] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:41] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:41] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:41] | code: 404
[2024-10-22T10:50:41] | }
[2024-10-22T10:50:41] | CrowdinError: File Not Found
[2024-10-22T10:50:41] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:41] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:41] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:41] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:41] | code: 404
[2024-10-22T10:50:41] | }
[2024-10-22T10:50:42] | CrowdinError: File Not Found
[2024-10-22T10:50:42] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:42] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:42] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:42] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:42] | code: 404
[2024-10-22T10:50:42] | }
[2024-10-22T10:50:42] | CrowdinError: File Not Found
[2024-10-22T10:50:42] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:42] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:42] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:42] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:42] | code: 404
[2024-10-22T10:50:42] | }
[2024-10-22T10:50:43] | CrowdinError: File Not Found
[2024-10-22T10:50:43] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:43] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:43] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:43] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:43] | code: 404
[2024-10-22T10:50:43] | }
[2024-10-22T10:50:43] | CrowdinError: File Not Found
[2024-10-22T10:50:43] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:43] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:43] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:43] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:43] | code: 404
[2024-10-22T10:50:43] | }
[2024-10-22T10:50:44] | CrowdinError: File Not Found
[2024-10-22T10:50:44] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:44] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:44] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:44] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:44] | code: 404
[2024-10-22T10:50:44] | }
[2024-10-22T10:50:46] | CrowdinError: File Not Found
[2024-10-22T10:50:46] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:46] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:46] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:46] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:46] | code: 404
[2024-10-22T10:50:46] | }
[2024-10-22T10:50:47] | CrowdinError: File Not Found
[2024-10-22T10:50:47] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:47] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:47] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:47] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:47] | code: 404
[2024-10-22T10:50:47] | }
[2024-10-22T10:50:48] | CrowdinError: File Not Found
[2024-10-22T10:50:48] | at handleHttpClientError (/workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:82:15)
[2024-10-22T10:50:48] | at /workspace/node_modules/@crowdin/crowdin-api-client/out/core/index.js:254:29
[2024-10-22T10:50:48] | at runMicrotasks (<anonymous>)
[2024-10-22T10:50:48] | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2024-10-22T10:50:48] | code: 404
[2024-10-22T10:50:48] | }


```

**Comment by thompsonsj** [comment]
Files that return a 404 from Crowdin are now deleted in Payload CMS. This resolves the file error (a 404 response is a clear and reliable indicator that the file was removed in Crowdin.

This is the most important change - as the files contain the translations.

Directory behaviour to follow.

For a summary - see https://github.com/thompsonsj/payload-crowdin-sync/issues/25.

**Comment by thompsonsj** [comment]
## Status check (Sep 2026)

Reviewed against current `main` / plugin API refactor.

### Files deleted on Crowdin — resolved

Handled in #213 (`feat(crowdinfiles): delete document if Crowdin API returns 404`). When translation fetch gets a Crowdin 404, the stale `crowdin-files` Payload document is deleted. Opt out via `disableSelfClean` in plugin config.

See also prior note in https://github.com/thompsonsj/payload-crowdin-sync/issues/147#issuecomment-2740588565.

### Directories deleted on Crowdin — still open

No directory equivalent of file self-clean yet. `findOrCreateCollectionDirectory` still reuses Payload `crowdin-collection-directories` records without verifying the directory exists on Crowdin; stale `originalId` values can still trigger *Invalid directory id given* errors.

Tracked in #360.

### UI / recreate missing files — still open (enhancement)

Follow-up comments about CMS UI reporting and recreate options are not implemented. Can be a separate enhancement issue if still wanted.

### Also since opened

- nock-based tests (precondition from original issue) ✓
- #341 — orphaned directory refs no longer block delete
- Name-conflict recovery when creating dirs/files on Crowdin

**Summary:** File handling from this issue is done (#213). Directory handling continues in #360. This issue can stay open for UI scope or be closed once #360 is addressed, depending on preference.

**Comment by thompsonsj** [comment]
Resolved in two parts:

- **Files:** #213 deletes stale `crowdin-files` records when Crowdin returns 404.
- **Directories:** #361 (tracked in #360) does the same for collection and article directory records, so the "Invalid directory id given. Directory doesn't exists" error no longer blocks syncing.

Both are covered by nock-based tests, which this issue suggested waiting for.
