### ISSUE TITLE
Errors on restore version

### ISSUE THREAD

**Issue by thompsonsj** [thompsonsj/payload-crowdin-sync#186]
Tried to restore a version from a different locale to the source locale - in case that matters.

```
[2024-08-14T10:02:03] | (payload): TypeError: doc[field.name].map is not a function
-- | --
[2024-08-14T10:02:03] | at /workspace/node_modules/payload-crowdin-sync/src/lib/utilities/index.js:375:18
[2024-08-14T10:02:03] | at Array.forEach (<anonymous>)
[2024-08-14T10:02:03] | at buildCrowdinJsonObject (/workspace/node_modules/payload-crowdin-sync/src/lib/utilities/index.js:361:20)
[2024-08-14T10:02:03] | at /workspace/node_modules/payload-crowdin-sync/src/lib/utilities/index.js:396:78
[2024-08-14T10:02:03] | at Array.map (<anonymous>)
[2024-08-14T10:02:03] | at /workspace/node_modules/payload-crowdin-sync/src/lib/utilities/index.js:394:18
[2024-08-14T10:02:03] | at Array.forEach (<anonymous>)
[2024-08-14T10:02:03] | at buildCrowdinJsonObject (/workspace/node_modules/payload-crowdin-sync/src/lib/utilities/index.js:361:20)
[2024-08-14T10:02:03] | at /workspace/node_modules/payload-crowdin-sync/src/lib/hooks/collections/afterChange.js:89:72
[2024-08-14T10:02:03] | at Generator.next (<anonymous>)
```

**Comment by thompsonsj** [comment]
Workaround for now - disable the plugin when restoring the version. e.g. comment out the API token from `.env`.
